### ISSUE TITLE
Beach island not deleting itself when we quit the domain in the console

### ISSUE THREAD

**Issue by frontline03** [NovaSector/NovaSector#4200] opened 2024-08-05 01:29 UTC
## Issue Summary
The Beach island brawl bitrunning mission does not properly delete it self after a mission. this means there is an excess of dead bodies and spawners in the map that are not capable of disappearing since the mission was ended but they did not delete. it also causes issues if we want to return to that mission since it will spawn us in the previous beach islands, not necessarily the first one, which if you look at the photos below, will not let us move and the only way out is by suiciding with the gun you spawn with. (aim at mouth and click on self with help intent)

## Reproduction: Use the bitrunning domain and go to the beach island as normal, it should be easy to replicate as it was caused simply by me just playing the mission.

![Screenshot 2024-08-05 021137](https://github.com/user-attachments/assets/2ea6fcc9-ac95-42ee-9089-122fa66da935)
![Screenshot 2024-08-05 021200](https://github.com/user-attachments/assets/44446350-8e8d-401f-a490-2ed6ea27e845)
![Screenshot 2024-08-05 021147](https://github.com/user-attachments/assets/5b1b8717-4f1d-4cd8-ada1-90d4ed0eaec0)

**Comment by Sadboysuss** [comment] 2024-08-05 09:22
Dupe of https://github.com/NovaSector/NovaSector/issues/4025

**Closed** 2024-08-05 09:22 UTC
