### ISSUE TITLE
bitrunners SPAWN IN SPACE on voidraptor

### ISSUE THREAD

**Issue by MaineTheMan** [NovaSector/NovaSector#876] opened 2024-02-09 23:56 UTC
## Issue Summary
as title says

## Testmerges: merged:
[#352: '[Semi-Modular]Ports over the old Food Prefs PR' by SomeRandomOwl at commit 71fc0938ab](https://github.com/NovaSector/NovaSector/pull/352)
[#372: 'And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor' by Paxilmaniac at commit 4160af2afd](https://github.com/NovaSector/NovaSector/pull/372)
[#453: 'Fundamental Equipment: roundstart loadout toolset implants' by Ephemeralis at commit 1bf366a5b4](https://github.com/NovaSector/NovaSector/pull/453)
[#497: 'Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit' by Paxilmaniac at commit ba2a15f1a2](https://github.com/NovaSector/NovaSector/pull/497)
[#603: '[MODULAR] Down By The River: Telepathy improvements & telepathic quirk' by Ephemeralis at commit 0f548e9043](https://github.com/NovaSector/NovaSector/pull/603)
[#561: 'Its Microver | Deletes all of microfusion | Adds the coolest energy weapons you have seen ever' by Paxilmaniac at commit 4adb5a7eb8](https://github.com/NovaSector/NovaSector/pull/561)
[#656: '[MODULAR] Oh God The Zipper's Stuck: Entombed quirk granting unremovable roundstart MODsuit' by Ephemeralis at commit 3efd2acf9d](https://github.com/NovaSector/NovaSector/pull/656)
[#350: 'Interdyne/DS2 Rising: Revengeance' by sqnztb at commit 468b22eda8](https://github.com/NovaSector/NovaSector/pull/350)
[#752: 'Unapologetic Moth Buffs Vol. II: The Ride' by Nerev4r at commit 14b1a70efa](https://github.com/NovaSector/NovaSector/pull/752)

**Comment by Floofies** [comment] 2024-02-10 00:04
Well, that's funny. Looks to be a easy fix!

![image](https://github.com/NovaSector/NovaSector/assets/17753498/0ad64864-40f9-4700-bd70-e00844925f62)

**Comment by Floofies** [comment] 2024-02-10 00:09
Possibly caused by PR #670

**Comment by Floofies** [comment] 2024-02-10 00:09
Will be fixed by PR #865

**Comment by Floofies** [comment] 2024-02-18 07:03
@vinylspiders 
This was fixed by fixed by PR #865

**Comment by Floofies** [comment] 2024-02-18 22:37
Fixed by PR #865

**Closed by Floofies** 2024-02-18 22:37 UTC
