### ISSUE TITLE
Lizards don't cool down via ambient air.

### ISSUE THREAD

**Issue by Drayco84** [NovaSector/NovaSector#201] opened 2023-12-30 22:01 UTC
## Issue Summary
Lizards will warm up via the ambient air, but don't cool down via the same methods.
This is great if you're standing in a low or normal pressure area and the temps are far below freezing as you'll never freeze to death (Tested in a room that was below 80 C.), but this sucks after getting overheated from spicy food (And getting horrible, disfiguring burns.) or being set on fire.

## Round ID:
Since Skyrat.

## Testmerges:
Since Skyrat.

## Reproduction:
Part 1: Be lizard. Grab a space heater and set it to stupidly low temps to the point where things instantly freeze. Strip naked for lols. Perform every dance emote because cold temps can't hurt you.
Part 2: Again, be lizard. Eat some spicy food. Watch yourself break out in severe, second degree burns. Run to medical. Watch as they treat the never-ending burn damage until the spicy leaves your body and SOMEBODY realizes that lizards need a external method to cool down and either hands you a cup of ice or injects you with cryoxodone or whatever.

**Comment by thegrb93** [comment] 2024-01-07 19:52
It's something to do with armor keeping you insulated. Taking off armor allows you to cool down, but I agree there's something really stupid about the current temperature system and it needs to be fixed on TG

**Comment by Sadboysuss** [comment] 2024-07-29 11:37
This isn't a bug, this is intended behavior upstream. The reason for this is cryo stings forcing you to take off armor when stung. I'll leave this open if you have anymore questions, it will be auto closed in 7 days.

**Comment by Drayco84** [comment] 2024-07-29 23:35
That's stupid. Taking off your armor should SPEED UP the warming process, but not BE REQUIRED for it. Is any other species REQUIRED to remove their armor to warm up from a cryo sting or beam? If not, why are lizards so damn special?

And also, like I previously said, being in a cold area doesn't freeze lizards and I'm pretty sure THAT'S unintended behavior as it makes absolutely no sense. Of all the other shit that's true-to-life in this game and lizards being unaffected by ambient temp flies in the face of all the other logic in the game.

**Comment by Sadboysuss** [comment] 2024-07-30 00:00
>  If not, why are lizards so damn special?

Bevause lizards are cold-blooded and can't regulate their own body temperature, while other species can. 
At the end of the day, players who make a conscious choice to play a specific race with downsides should accept the downsides and whatever difficulties arise from them, helping generate a more unique storyline and playstyle for the player.

**Comment by thegrb93** [comment] 2024-07-30 00:51
I'll take a look at the code since TG devs neglect lizards so much

**Comment by Drayco84** [comment] 2024-07-30 01:07
> > If not, why are lizards so damn special?
> 
> Because lizards are cold-blooded and can't regulate their own body temperature, while other species can. At the end of the day, players who make a conscious choice to play a specific race with downsides should accept the downsides and whatever difficulties arise from them, helping generate a more unique storyline and playstyle for the player.

That's why I'm saying that this is stupid. My whole problem with this (Which is something that, YET AGAIN, I failed to put into words.) is that lizard body temp SHOULD BE regulated by the surrounding air temp instead of being unaffected by it. One "intended" effect gained via a bug from another bit of jank code doesn't mean that it "works as intended". In short, some code isn't working as it should be so somebody had to make janky, bugged code to fix the OG bug. That's part of why SS13 code is such a janky, buggy mess.

My whole bug complaint is that lizards aren't effected by the ambient/air temp around them in terms of heating AND cooling when as a cold-blooded species, they SHOULD more than anything else, the effect of cryo stings or cryo gazes be damned.

**Comment by Sadboysuss** [comment] 2024-07-30 01:28
> lizards aren't effected by the ambient/air temp around them in terms of heating AND cooling

They are, though, just not when clothing insulated with armor, for example.

**Comment by thegrb93** [comment] 2024-07-30 01:56
So, it looks like the temperature can get stuck. I'm trying to see why now.

**Comment by thegrb93** [comment] 2024-07-30 02:40
https://github.com/tgstation/tgstation/pull/85401

**Comment by Sadboysuss** [comment] 2024-07-30 20:15
https://github.com/tgstation/tgstation/pull/85401

**Closed by Sadboysuss** 2024-07-30 20:15 UTC
Labels: Not a Bug, TG Upstream Issue, Cleanup Flagged

**Comment by Sadboysuss** [comment] 2024-08-04 13:42
this has caused more issues upstream than it solved so someone opened a revert for it: https://github.com/tgstation/tgstation/pull/85604

**Comment by thegrb93** [comment] 2024-08-04 15:58
Might have to be done in skyrat code. TG devs are fucking idiots

**Comment by thegrb93** [comment] 2024-08-04 15:58
Might have to be done in skyrat code if the TG devs don't reconsider it.

**Comment by Sadboysuss** [comment] 2024-08-04 17:22
> Might have to be done in skyrat code if the TG devs don't reconsider it.

There's a reason for the revert. The change ended up making lizards die in MODsuits, and lizards would die on icebox from cold while wearing winter coats.
It's a good idea, just needs revision

**Comment by thegrb93** [comment] 2024-08-04 18:30
They die because they don't regulate body temperature, the only reason survived before is because of the insulation jank. A modsuit thermal regulator or a space suit with thermal regulator would let them survive in those environments. So I'm going to make a new PR with the fix, but give lizards the ability to regulate body temp.

**Comment by thegrb93** [comment] 2024-08-04 20:05
They're being a pain in the ass about it so whatever.
