### ISSUE TITLE
Cyborgs situationally cannot be linked to the station AI

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [NovaSector/NovaSector#2279] opened 2024-05-01 23:32 UTC
Reporting client version: 515.1623

## Issue Summary

I was teaching a newer Roboticist how to link an unlinked cyborg to the station AI, because the previous AI had left and a new one arrived. So we open up the cyborg and it's not working. I get them to read out to me which wires are labelled for them (because I'm off-duty at the time) and we pulse the wire that links the cyborgs to the AI. No dice. So I have them cut and mend the wire. No dice. I build a Robotics Control Console to see for ourselves nothing has worked, and at this point I'm getting the feeling it's because M.A.I.D. (the cyborg in question) is using a polymorph module to look like a syndicate version of themselves for the sake of drip. So I conclude we need to dismantle and rebuild them, but to save the upgrades, first I got her to reset MAID's module and forcedrop the upgrades. Then before we dismantled them, to test my theory I had Amy try to sync MAID again. This time it worked, and we simply let them pick their module again, shoved the upgrades back in, and sent them on their way. Not sure what it could've been but my gut tells me it's was the polymorph.
## Round ID:
[10729](https://scrubby.melonmesa.com/round/10729)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [Adds more spawn location to moldies](https://github.com/NovaSector/NovaSector/pull/2134)
- [Ouroboros rejigging](https://github.com/NovaSector/NovaSector/pull/2088)
- [[Semi-Modular] Ports over additional Crusher varients from monkestation](https://github.com/NovaSector/NovaSector/pull/2238)

## Reproduction:

Attempt to re-link an unlinked cyborg by pulsing the right wire, see that it didn't work when the cyborg is polymorphed into a syndicate cyborg. Pray to Synthetica for succor from this jankiness.

**Comment by Sadboysuss** [comment] 2024-07-31 18:11
I don't think this is an issue anymore, if you still see it happening - leave a comment here. 
The issue is marked for cleanup and will be auto-closed in 7 days otherwise.

**Closed** 2024-08-08 00:55 UTC
Labels: TG Upstream Issue, Cleanup Flagged
