### ISSUE TITLE
Number insertions borked

### ISSUE THREAD

**Issue by annikaRU** [NovaSector/NovaSector#332] opened 2024-01-06 08:52 UTC
Reporting client version: 514.1589

## Issue Summary

When inserting custom numbers into something you print or musical instruments it will not insert the selected number or will not insert
![image](https://github.com/NovaSector/NovaSector/assets/147753662/e727ae9b-5cf1-4b5e-96f9-01803832a053)
EG: insert 25 and it stays as 1

Same thing applies to chameleon card age, you can either only select 18 or the max age

The one recorder electric music thing, the same applies to the rhythm or something

## Round ID:
[10439](https://scrubby.melonmesa.com/round/10439)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[TM ONLY] [EARLY MIRROR] Revert "Makes immerse use weakrefs", prioritizing some ref removal lines instead](https://github.com/NovaSector/NovaSector/pull/238)
- [[MODULAR] Removes Arbitrary Loadout Restrictions](https://github.com/NovaSector/NovaSector/pull/58)
- [[MODULAR] Chat color tweaks!](https://github.com/NovaSector/NovaSector/pull/323)
- [Kahraman, after collecting dust for 100 years, finally has its own content, hear ye guncargo naysayers and weep](https://github.com/NovaSector/NovaSector/pull/98)
- [[TM-ONLY] Testing chatmessage debug](https://github.com/NovaSector/NovaSector/pull/275)

## Reproduction:

Esentially pull up anything to insert custom numbers like the photo I provided above, insert a number say 25 or 30, it will remain as one and cannot be edited to be changed

**Comment by Floofies** [comment] 2024-01-12 19:37
Reproduced on Nova main and local. Some number inputs are OK, while the inputs described are buggy.

The synthesizer uses `tgui_input_number` to set things like Linear Sustain Duration, that seems to be bugged.

**Comment by Floofies** [comment] 2024-02-25 19:59
Hi! Is this still an issue?
Supposedly this issue was fixed by #1037

**Comment by annikaRU** [comment] 2024-02-25 20:22
I believe this was fixed will close this as I havent encountered it

**Closed** 2024-02-25 20:22 UTC
Labels: Bug
